import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/common/Header/Header";
import Footer from "./components/common/Footer/Footer";
import WrapperLayout from "./components/common/WrapperLayout/WrapperLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FoodFest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WrapperLayout>{children}</WrapperLayout>
      </body>
    </html>
  );
}

